---
name: "Automerge pull request"
description: "Automatically merges a GitHub pull request that has passed checks"
author: "Rod Oliver"
inputs:
  host:
    description: "The GitHub host"
    required: false
    default: "github.tools.sap"
  org:
    description: "The GitHub organisation"
    required: false
    default: "netinfra"

runs:
  using: "docker"
  image: "Dockerfile"
