name: Test
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on:
      - self-hosted
    steps:
      - name: Get the source
        uses: actions/checkout@v2
      - name: Automerge a PR
        uses: ./
        env:
          GH_ENTERPRISE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_HOST: ${{ env.INPUT_HOST }}
