---
name: Test
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on:
      - self-hosted
    steps:
      - name: Get the source
        uses: actions/checkout@v2
      - name: Automerge a PR
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
