name: Test
on:
  pull_request:
    branches:
      - main
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the source
        uses: actions/checkout@v2
      - name: Automerge a PR
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
